/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LogbookRouteImport } from './routes/logbook'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as CurrencyRouteImport } from './routes/currency'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksOgnSyncRouteImport } from './routes/api/public/hooks/ogn-sync'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LogbookRoute = LogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const CurrencyRoute = CurrencyRouteImport.update({
  id: '/currency',
  path: '/currency',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksOgnSyncRoute = ApiPublicHooksOgnSyncRouteImport.update({
  id: '/api/public/hooks/ogn-sync',
  path: '/api/public/hooks/ogn-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/currency': typeof CurrencyRoute
  '/fleet': typeof FleetRoute
  '/history': typeof HistoryRoute
  '/logbook': typeof LogbookRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/public/hooks/ogn-sync': typeof ApiPublicHooksOgnSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/currency': typeof CurrencyRoute
  '/fleet': typeof FleetRoute
  '/history': typeof HistoryRoute
  '/logbook': typeof LogbookRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/public/hooks/ogn-sync': typeof ApiPublicHooksOgnSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/currency': typeof CurrencyRoute
  '/fleet': typeof FleetRoute
  '/history': typeof HistoryRoute
  '/logbook': typeof LogbookRoute
  '/members': typeof MembersRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/api/public/hooks/ogn-sync': typeof ApiPublicHooksOgnSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/billing'
    | '/currency'
    | '/fleet'
    | '/history'
    | '/logbook'
    | '/members'
    | '/settings'
    | '/stats'
    | '/api/public/hooks/ogn-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/billing'
    | '/currency'
    | '/fleet'
    | '/history'
    | '/logbook'
    | '/members'
    | '/settings'
    | '/stats'
    | '/api/public/hooks/ogn-sync'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/billing'
    | '/currency'
    | '/fleet'
    | '/history'
    | '/logbook'
    | '/members'
    | '/settings'
    | '/stats'
    | '/api/public/hooks/ogn-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  CurrencyRoute: typeof CurrencyRoute
  FleetRoute: typeof FleetRoute
  HistoryRoute: typeof HistoryRoute
  LogbookRoute: typeof LogbookRoute
  MembersRoute: typeof MembersRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  ApiPublicHooksOgnSyncRoute: typeof ApiPublicHooksOgnSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logbook': {
      id: '/logbook'
      path: '/logbook'
      fullPath: '/logbook'
      preLoaderRoute: typeof LogbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/currency': {
      id: '/currency'
      path: '/currency'
      fullPath: '/currency'
      preLoaderRoute: typeof CurrencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ogn-sync': {
      id: '/api/public/hooks/ogn-sync'
      path: '/api/public/hooks/ogn-sync'
      fullPath: '/api/public/hooks/ogn-sync'
      preLoaderRoute: typeof ApiPublicHooksOgnSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  CurrencyRoute: CurrencyRoute,
  FleetRoute: FleetRoute,
  HistoryRoute: HistoryRoute,
  LogbookRoute: LogbookRoute,
  MembersRoute: MembersRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  ApiPublicHooksOgnSyncRoute: ApiPublicHooksOgnSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
