/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MembersRouteImport } from './routes/members'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksOgnSyncRouteImport } from './routes/api/public/hooks/ogn-sync'

const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksOgnSyncRoute = ApiPublicHooksOgnSyncRouteImport.update({
  id: '/api/public/hooks/ogn-sync',
  path: '/api/public/hooks/ogn-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fleet': typeof FleetRoute
  '/members': typeof MembersRoute
  '/api/public/hooks/ogn-sync': typeof ApiPublicHooksOgnSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fleet': typeof FleetRoute
  '/members': typeof MembersRoute
  '/api/public/hooks/ogn-sync': typeof ApiPublicHooksOgnSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/fleet': typeof FleetRoute
  '/members': typeof MembersRoute
  '/api/public/hooks/ogn-sync': typeof ApiPublicHooksOgnSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/fleet'
    | '/members'
    | '/api/public/hooks/ogn-sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/fleet' | '/members' | '/api/public/hooks/ogn-sync'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/fleet'
    | '/members'
    | '/api/public/hooks/ogn-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  FleetRoute: typeof FleetRoute
  MembersRoute: typeof MembersRoute
  ApiPublicHooksOgnSyncRoute: typeof ApiPublicHooksOgnSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ogn-sync': {
      id: '/api/public/hooks/ogn-sync'
      path: '/api/public/hooks/ogn-sync'
      fullPath: '/api/public/hooks/ogn-sync'
      preLoaderRoute: typeof ApiPublicHooksOgnSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  FleetRoute: FleetRoute,
  MembersRoute: MembersRoute,
  ApiPublicHooksOgnSyncRoute: ApiPublicHooksOgnSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
